#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions
#------------------------------------------------------------------------------

cleanCase
rm -rf 0 VTKs open.foam

#------------------------------------------------------------------------------
